### ISSUE TITLE
Can't add mods released as alpha.

### ISSUE THREAD

**Issue by juraj-hrivnak** [froehlichA/pax#54]
### The issue
I wanted to add this mod to my modpack: https://www.curseforge.com/minecraft/mc-mods/multithreaded-noise, 
but it's released as alpha, and apparently, pax won't let me do that.

```bash
$ pax add Multithreaded Noise
[:] Loading data from manifest..
[:] Searching for mod..
[x] No compatible version found.
```

**Comment by froehlichA** [comment]
PAX should normally fallback to different version resolutions so if the "recommended" strategy cant find any files the "newest" strategy is applied, which will allow any mod files matching your modpacks major version.

This mod is 1.12, are you sure your modpacks version is set to `1.12` (or `1.12.1` or `1.12.2`)?

**Comment by juraj-hrivnak** [comment]
Ahah, so that issue is in the Minecraft version. The modpack is set to `1.12.2`.
Here is my `manifest.json`: https://pastebin.com/UTYJ7kKq

So, the issue is that this mod also works for `1.12.2` and not only `1.12`.
Yeah, it's the mods fault, but it would be nice to be able to ignore the mc versions in Pax, just in case if the mod author forgets to add the newest mc version in the compatible versions.

**Comment by froehlichA** [comment]
Normally Pax allows installation of mods with the same major version as the modpack, so this seems more like a bug. Ill take a look at this issue later today.

**Comment by juraj-hrivnak** [comment]
Thank you! I've been really enjoying using the Pax lately. It is also easy to use, just like you said. It reminds me of Node Package Manager. I really appreciate your work!

**Comment by froehlichA** [comment]
Oh, I see what's going on: The curseforge search API is pure shit, and when searching for "Multithreaded noise", instead of returning the mod LITERALLY called "Multithreaded noise", it will return a mod called "Annoing mod warning loud noise", because apparently full text search is still SO difficult in 2021.

When the curseforge search API only returns one item, PAX assumes this is the mod you want and skips selecting mods out of the list, never telling you what mod it actually selected.

I can't fix the curseforge api, but I can *kinda* prevent users not knowing what went wrong by echoing what mod was actually selected before pax tries to install it, which could give future users at least some feedback that the wrong mod was selected.

---

Btw, this doesn't solve your issue of course, you'll need to add the mod with the curseforge URL:

```bash
./pax add https://www.curseforge.com/minecraft/mc-mods/multithreaded-noise
```

which should resolve to the correct mod.
