### ISSUE TITLE
Error when running `./pax ls` or `upgrade`

### ISSUE THREAD

**Issue by juraj-hrivnak** [froehlichA/pax#67]
### The issue
The folowing error showed up every time when I tried the `./pax ls` or `upgrade` command:
```bash
httpclient.nim(308)      httpError
asyncfutures.nim(372)    read
asyncfutures.nim(372)    read
asyncfutures.nim(372)    read
asyncfutures.nim(372)    read
asyncfutures.nim(372)    read
asyncfutures.nim(372)    read
asyncfutures.nim(372)    read
???                      fetchAddonIter
asyncfutures.nim(372)    read
Error: unhandled exception: Connection was closed before full request has been made [ProtocolError]
```
The version of PAX is **1.9.8**

**Comment by juraj-hrivnak** [comment]
Something has changed. `./pax upgrade` is working for me now. And `./pax ls` throws this error now:
```vim
options.nim(185)         get
Error: unhandled exception: Can't obtain a value from a `none` [UnpackDefect]
```

Also, here is my manifest: [manifest.zip](https://github.com/froehlichA/pax/files/8308052/manifest.zip)

**Comment by froehlichA** [comment]
This sounds like a different issue.
Thanks for sending the manifest, I'll try to reproduce this one this weekend ^^

**Comment by Riku5543** [comment]
I'm getting this error with a fairly big pack while trying to use `pax ls`. My guess is that we're being ratelimited or something

**Comment by froehlichA** [comment]
The bulk endpoint was getting a bit overloaded when you send in 300 mods at once. I've switched to another curseforge proxy that supports caching and rewrote the bulk endpoints so that it falls back to the "normal" endpoints if the bulk ones don't work.

This should be fixed in https://github.com/froehlichA/pax/releases/tag/v1.9.9 - I've tested it with your manifest, it is still very very slow, which is why I'm implementing https://github.com/froehlichA/pax/issues/25 next, but it should not throw an error anymore.
